export const products = [
  {
    id: 1,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1657389256/WhatsApp_Image_2022-07-09_at_11.23.55_PM_i2fwzv.jpg",
    link: "https://github.com/HasithDeminda/Research-Managment-System-1",
    topic: "Research Management System",
    stack: "React, Redux, Nodejs, MongoDB, Express, Bootstrap, JWT ",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1631274494/kryei1hcowdawldxifiv.png",
    link: "https://github.com/HasithDeminda/Institution-Management-System",
    topic: "Institute Management System",
    stack: "React, Redux, Nodejs, MongoDB, Express, Bootstrap, JWT ",
  },

  {
    id: 2,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1657389560/Screenshot_2022-07-09_232856_ng9bet.png",
    link: "https://github.com/HasithDeminda/Fitness_WebApplication_MERN_Stack",
    topic: "Fitness Center Web Application",
    stack: "React, Nodejs, MongoDB, Express, Bootstrap",
  },
  {
    id: 2,
    img: "https://cdn.dribbble.com/users/1664848/screenshots/4828362/__app_.png?compress=1&resize=400x300&vertical=top",
    link: "https://github.com/HasithDeminda/Movie-Reservation-Android-App",
    topic: "Movie Reservation Android App",
    stack: "Java, Android Studio, SQLite",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1636642025/Screenshot_2_ym8usq.png",
    link: "https://res.cloudinary.com/desnqqj6a/video/upload/v1636457815/ProjectTrailer2_zuatcl.mp4",
    topic: "Event Management Web Application",
    stack: "HTML, CSS, JavaScript, Java(servlets), MySQL, Bootstrap, JWT",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1657387477/Screenshot_2022-07-09_225420_u72w89.png",
    link: "#",
    topic: "Personal Portfolio Website",
    stack: "React, CSS/SASS, Context API",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1636551639/screencapture-file-F-Semester-2-IWT-IWTFinal-IWTL-Php-newHome-html-2021-11-10-15_53_11_xzyffp.png",
    link: "#",
    topic: "Online Recipe Management System",
    stack: "HTML, CSS, JavaScript, Php, MySQL, Bootstrap, JWT Authentication",
  },
  {
    id: 6,
    img: "https://storage.needpix.com/rsynced_images/ecommerce-1992281_1280.png",
    link: "https://github.com/HasithDeminda/Online-Shopping-Store",
    topic: "E-Commerce Web Application",
    stack: "React, Redux, Nodejs, MongoDB, Express, Bootstrap, JWT ",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/desnqqj6a/image/upload/v1636643993/pinpng.com-coming-soon-sign-png-6134709_n9yqhd.png",
    link: "#",
    topic: "Movie Browser Web Application ( Still in Development )",
    stack: "React, Redux, Nodejs, MongoDB, Express, Bootstrap, JWT and etc ",
  },
];
